Repository zephyrproject-rtos/sdk-ng, pull requests merged in 2022-08, with the labels that each got.

#533 ci: Replace intel_s1000_crb with intel_adsp_cavs18
  .github/workflows/ci.yml
Labels: area: CI

#534 meta-zephyr-sdk: arc_qemu: Update to 2022.08.04 release
  meta-zephyr-sdk/recipes-devtools/arc_qemu/arc-qemu_git.bb
Labels: area: QEMU

#531 ARC: ARCv3: fix toolchain prefix for ARCv3 32bit
  cmake/zephyr/target.cmake
Labels: area: Toolchain

#538 ci: Install ninja and meson
  .github/workflows/ci.yml
Labels: area: CI

#551 doc: readme: Add note on patch testing workflow
  README.md
Labels: area: Documentation
