Repository zephyrproject-rtos/sdk-ng, pull requests merged in 2022-11, with the labels that each got.

#583 scripts: template_setup_posix: Fix Linux OS type detection
  scripts/template_setup_posix
Labels: platform: Linux, area: Distribution Bundle

#586 meta-zephyr-sdk: Downgrade glibc to 2.27
  meta-zephyr-sdk/scripts/meta-zephyr-sdk-clone.sh
Labels: area: Distribution Bundle, area: Host Tools

#587 aarch64: Add -moverride=tune=no_ldp_stp_qregs to TARGET_CFLAGS
  configs/aarch64-zephyr-elf.config
Labels: area: GCC

#589 Disable TLS for GCC on targets with no Zephyr support
  configs/mips-zephyr-elf.config
  configs/nios2-zephyr-elf.config
  configs/xtensa-espressif_esp32_zephyr-elf.config
  configs/xtensa-espressif_esp32s2_zephyr-elf.config
  configs/xtensa-intel_apl_adsp_zephyr-elf.config
  configs/xtensa-intel_bdw_adsp_zephyr-elf.config
  configs/xtensa-intel_byt_adsp_zephyr-elf.config
  configs/xtensa-intel_s1000_zephyr-elf.config
  configs/xtensa-nxp_imx8m_adsp_zephyr-elf.config
  configs/xtensa-nxp_imx_adsp_zephyr-elf.config
  configs/xtensa-sample_controller_zephyr-elf.config
Labels: area: GCC

#595 arc: Add -mtp-regno=26 to CFLAGS
  configs/arc-zephyr-elf.config
Labels: area: GCC

#597 template_setup_posix: Fix command line toolchain flag handling
  scripts/template_setup_posix
Labels: area: Distribution Bundle

#604 ci: Use AArch64 zephyr-runner to natively build and test AArch64 Linux and macOS toolchains
  .github/workflows/ci.yml
Labels: area: CI, platform: Linux, platform: macOS, area: Distribution Bundle, area: Testing

#582 qemu: Enable KVM
  meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
Labels: area: QEMU
